//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> LopId { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
